# Generated by Django 4.1.1 on 2022-10-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_category_alter_room_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='', max_length=180, null=True),
        ),
    ]
