# Generated by Django 4.1.1 on 2022-10-31 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
    ]
